const assert = require('node:assert/strict');
const fs = require('node:fs');
const service = fs.readFileSync('server/services/ragic.js', 'utf8');
const admin = fs.readFileSync('server/services/ragicAdmin.js', 'utf8');
assert.ok(!service.includes('runCanaryWriteReadProof'));
assert.ok(!service.includes('_writeCanaryNonce'));
assert.match(admin, /canary_configured:\s+null/);
const gate = admin.match(/async function hasRecentSuccessfulPull[\s\S]*?\n}/)[0];
assert.match(gate, /status = 'ok'/);
assert.match(gate, /created_at >= NOW\(\)/);
assert.ok(!gate.includes('freshness_verified'));
console.log('ragic_canary_state: PASS retired; successful pull still required');
